spring.application.name=factor-App

spring.data.mongodb.uri=mongodb+srv://SouravJaiswaldb:5CIybf9Nnz2Vq0UU@cluster0.65z31fr.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true
